spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:reportdb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect