spring:
  profiles:
    active: h2
  application:
    name: ea-project-receiver
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
server:
  port: 8081
app:
  version: @project.version@
  messaging:
    queue: emr.reports
